### PR TITLE
Created the Semaphore config and added a Rubocop block

### PR DESCRIPTION
**Pull request by vivek-viswam-rv**
Part of: https://github.com/bigbinary/neeto-engineering-web/issues/277

@navaneethsdk _a Please add the `.rubocop.yml` file.

cc: @yedhink

### CODE REVIEW

**Comment by navaneethsdk** [comment]
@vivek-viswam-rv _a. I have added and applied fixes.

**Comment by vivek-viswam-rv** [comment]
@yedhink _a Please review the changes.

**Comment by yedhink** [comment]
@AbhayVAshokan _a Can you please review and merge this?

**Review by AbhayVAshokan — APPROVED** [review]
LGTM

**Pull request merged**
